### ISSUE TITLE
Initialize Project

### ISSUE THREAD

**Issue by mmavroudi** [mmavroudi/Blog#1]
1.Install django and requirements
2.Include Bootstrap v5.2 via cdn

**Comment by kkampardi** [comment]
@mmavroudi 
for step 1 example can be found here 
https://www.udemy.com/course/django-3-build-portfolio-project-with-django-from-scratch/learn/lecture/28318450#overview
 for step 2 an example is demonstrated here in this course
https://www.udemy.com/course/django-3-build-portfolio-project-with-django-from-scratch/learn/lecture/28318634#overview

**Comment by kkampardi** [comment]
Done
