### ISSUE TITLE
Blog Post View

### ISSUE THREAD

**Issue by kkampardi** [mmavroudi/Blog#13]
# Task
Create a new view in django for the  for the blog post

1. Create a new model named `Post`  for posts with fields: **slug, title, content and image** **DONE**
2. Create a new url configuration for blog post page (`post_detail_view`) **DONE**
    (each view has its own url configuration ) 
     The path to the url should be like
     /posts  (eg:  http://127.0.0.1:8000/posts
     An example of what we want to create here is demonstrated in the  the Portfolio tutorial here in [this lecture](https://www.udemy.com/course/django-3-build-portfolio-project-with-django-from-scratch/learn/lecture/28318550#content)
     See the example before start working
3. Render recent (10 ) blog posts in home page: 
    We need blog post data in our database to render the in /posts page
    On the Portfolio tutoral  check out the following lectures in  **Section 3: Django Databases** 
    Play
        12. Django Migrations ( to migrate new database model Posts )
        13. Creating Superuser for Django (to have access in admin)
       Note:_14 and 15 are the most important to add data in Posts table_
        **14. Adding Projects App to Django Admin
        15. Adding Projects to Database**
       Note  _16 and 17 are just to play with admin interface_
        17. Setting Titles in Django Admin
        18. Adding Filter in Django Admin
        
5. Create a new view for blog post details: **DONE** in `post_detail_view`
6. Add a query for Posts in `post_detail_view` similar to what described here
 https://www.udemy.com/course/django-3-build-portfolio-project-with-django-from-scratch/learn/lecture/28318630#content
7. Render Posts in /posts - basic HTML 
 https://www.udemy.com/course/django-3-build-portfolio-project-with-django-from-scratch/learn/lecture/28318632#content

start working on a new branch blog-posts

**Comment by mmavroudi** [comment]
Still a little bit confused about views. I couldn't complete task 3. I think it's because of my lack of knowledge in the django - python programming field.
