### ISSUE TITLE
Create new page test for product same as sixdogsrecords 

### ISSUE THREAD

**Issue by mmavroudi** [mmavroudi/Blog#51]

**Comment by kkampardi** [comment]
If you are to deliver the work done for this ticket/branch you need to create a new PR for this branch/ticket and assign the review for this PR to me.

**How the workflow should be, when working remotely using GH**:

- You get the ticket assigned to you
- Work on the ticket on a **new** branch
- Open a PR when you are ready to deliver the work 
- Assign a collaborator for code review

 ... and then you can start working on the next ticket you have on your plate
 
That is how it works, and **you do this every for every new ticket you are working** on

new ticket =  new branch

 I'm sending this back to you @mmavroudi
