### ISSUE TITLE
Post details page aside block

### ISSUE THREAD

**Issue by kkampardi** [mmavroudi/Blog#55]
# Task
Render dynamic posts in the aside-block in single post page
![aside-block](https://user-images.githubusercontent.com/8265472/211545632-9bb84926-6d56-4e6f-a7b1-801a3143cf02.jpg)

-  For tab popular render 6 posts that have the 'popular' tag
-  For tab  tranding render 6 posts that have 'trending' tag
-  For tab latest  render 6 posts ordered by date (latest)

**Comment by mmavroudi** [comment]
The latest section does not render right. It renders all posts and not just the 6 latest. I will continue tomorrow to find the right way to fix it.

**Comment by kkampardi** [comment]
> The latest section does not render right. It renders all posts and not just the 6 latest. I will continue tomorrow to find the right way to fix it.

Regarding these, notes are added in the pull request
Let's find out how to **query n records  in django**

**Comment by kkampardi** [comment]
@mmavroudi changes look good 
Lets not spend more time on this project
